# Default configuration of the paper.
base_path: /data/rsourave/datasets/GTEA
batch_size: 32
epochs: 100
length: 32
lr: 0.00005
momentum: 0.5
shuffle: true
videos:
- 0
- 1
- 5
- 6
- 7
- 8
- 9
- 11
- 12
- 14
- 15
viewers:
- 0
output_dir: /data/rsourave/DFG_Gaze_Saved/GTEA/
generator_saved_model: /data/rsourave/DFG_Gaze/GTEA/36/epochs/


